[package]
authors = ["Benoît Zugmeyer <bzugmeyer@gmail.com>"]
name = "advent_of_code_2017"
version = "0.1.0"

[lib]
name = "aoc2017"
path = "src/lib.rs"

[dependencies]
itertools = "0.7.3"
nom = "3.2.1"
regex = "0.2.3"
