[package]
name = "aoc-2020"
version = "0.1.0"
authors = ["Benoît Zugmeyer <bzugmeyer@gmail.com>"]
edition = "2018"

[dependencies]
native-tls = "0.2.3"
itertools = "0.9.0"
bytecount = "0.6.0"
lazy_static = "1.4.0"
